# Generated by Django 5.2.4 on 2025-07-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='product/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
